name: Trigger deployment on pull request and changes to pr
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Trigger deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        environment: prod

      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
